### ISSUE TITLE
Setup Mac

### ISSUE THREAD

**Issue by codemis** [codemis/ruminate#3]
- [x] Open Macbook Pro Box
- [x] Pull Out Mac
- [x] Turn on Mac
- [ ] Setup your Mac
- [x] Unplug PC
- [ ] Dig Hole
- [ ]  Throw your PC In
- [ ] Cover Hole
- [ ] Walk Away

**Comment by thecodewarrior** [comment]
Don't forget:
- [ ] Build fire above pit
- [ ] Ignore the toxic fumes
